//export const API_URL = "http://10.0.2.2:8888"
export const API_URL = "https://memoneo-api.herokuapp.com"
export const SECURE_STORE_HASH_KEY = "hash"
export const SECURE_STORE_ENCRYPTION_KEY = "text_enc"
export const DEFAULT_SALT = "iu41hk2jdlahsh784i1232jkjndsahkl"
export const DEFAULT_IV = "idlahs3dj1ldlk09"